### ISSUE TITLE
Unexpected token error on new install

### ISSUE THREAD

**Issue by bthomas14** [html-next/ember-hammertime#32]
Trying to install (currently on Ember 1.13.8) and keep getting and unexpected token error: 
Unexpected token ,
.../node_modules/ember-hammertime/htmlbars-plugins/touch-action.js:122
  TouchActionSupport,

**Comment by bthomas14** [comment]
Sorry, just realized I needed to install an earlier version of hammertime compatible with Ember 1.13.

**Comment by runspired** [comment]
Thanks for coming back to clarify!
